---
name: Matrix Test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        m-abc:
          - "a"
          - "b"
          - "c"
        m-xyz:
          - "x"
          - "y"
          - "z"
      fail-fast: false
    steps:
      - run: |
          echo "Running matrix based test"
          echo
          echo "  m-abc: ${{ matrix.m-abc }}"
          echo "  m-xyz: ${{ matrix.m-xyz }}"

          # Force fail if input is "a" and "z"
          if [[ ${{ matrix.m-abc }} == "a" && ${{ matrix.m-xyz }} == "z" ]]; then return 1; fi
